"""Tests for the Qwen lock-derived Hemma requirements export.

Purpose:
    Preserve the separately installed ROCm GPU runtime while deriving the
    remaining Qwen container requirements from the nested project lock.

Relationships:
    - Covers `export_qwen_requirements.py`.
    - Protects the TASK-383 ROCm Torch ownership boundary.
"""

from __future__ import annotations

from scripts.sir_convert_a_lot.devops.export_qwen_requirements import (
    filter_container_requirements,
)


def test_filter_container_requirements_excludes_separately_owned_gpu_packages() -> None:
    exported = """\
# generated by pdm export
numpy==2.4.6
torch==2.10.0 ; python_version >= "3.12"
torchaudio==2.10.0
torchvision==0.25.0
triton==3.5.1
cuda-toolkit==13.0.3.0 ; platform_system == "Linux"
nvidia-cublas==13.1.1.3 ; platform_system == "Linux"
transformers==4.57.3
"""

    filtered = filter_container_requirements(exported)

    assert (
        filtered
        == """\
# generated by pdm export
numpy==2.4.6
transformers==4.57.3
"""
    )
