"""Generate narrow service dependency-image input contracts.

Purpose:
    Build the deterministic dependency hash used by Sir Convert-a-Lot service
    dependency images without letting PDM scripts, tool configuration, or
    unrelated project metadata affect heavyweight Docker cache keys.

Relationships:
    - Consumes the filtered service requirements generated by
      `export_service_requirements.py`.
    - Reads only ROCm/CPU runtime pins from `service_image_build_contract.py`.
    - Writes `docker/service-deps/` artifacts consumed by `Dockerfile.deps`.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

from scripts.sir_convert_a_lot.devops.service_image_build_contract import (
    CpuRuntimeContract,
    RocmRuntimeContract,
    load_cpu_runtime_contract,
    load_rocm_runtime_contract,
)

RuntimeKind = Literal["rocm", "cpu"]

SCHEMA_VERSION = 1
DEFAULT_EASYOCR_LANGUAGES = ("sv", "en")
DEFAULT_EASYOCR_MODEL_STORAGE_DIRECTORY = "/opt/easyocr-models"


@dataclass(frozen=True)
class EasyOcrPreloadContract:
    """Stable EasyOCR preload inputs baked into dependency images."""

    languages: tuple[str, ...] = DEFAULT_EASYOCR_LANGUAGES
    gpu: bool = False
    model_storage_directory: str = DEFAULT_EASYOCR_MODEL_STORAGE_DIRECTORY
    download_enabled: bool = True

    def as_json_object(self) -> dict[str, object]:
        """Return a deterministic JSON-compatible representation."""
        return {
            "download_enabled": self.download_enabled,
            "gpu": self.gpu,
            "languages": list(self.languages),
            "model_storage_directory": self.model_storage_directory,
        }


def _sha256_text(value: str) -> str:
    """Return the SHA-256 hex digest for text content."""
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def _canonical_json(payload: dict[str, object]) -> str:
    """Serialize a payload with stable key and whitespace settings."""
    return json.dumps(payload, ensure_ascii=True, indent=2, sort_keys=True) + "\n"


def dependency_input_hash(payload: dict[str, object]) -> str:
    """Return the stable dependency hash for a generated input payload."""
    hash_payload = {key: value for key, value in payload.items() if key != "dependency_hash"}
    canonical_payload = json.dumps(
        hash_payload,
        ensure_ascii=True,
        separators=(",", ":"),
        sort_keys=True,
    )
    return _sha256_text(canonical_payload)


def rocm_runtime_pins_json(contract: RocmRuntimeContract) -> dict[str, object]:
    """Return the selected ROCm runtime pins that affect dependency images."""
    return {
        "torch_index_url": contract.torch_index_url,
        "torch_version": contract.torch_version,
        "torchaudio_version": contract.torchaudio_version,
        "torchvision_version": contract.torchvision_version,
    }


def cpu_runtime_pins_json(contract: CpuRuntimeContract) -> dict[str, object]:
    """Return the selected CPU runtime pins that affect dependency images."""
    return {
        "torch_version": contract.torch_version,
        "torchaudio_version": contract.torchaudio_version,
        "torchvision_version": contract.torchvision_version,
    }


def build_dependency_input_payload(
    *,
    requirements_text: str,
    runtime_kind: RuntimeKind,
    runtime_pins: dict[str, object],
    easyocr_preload: EasyOcrPreloadContract = EasyOcrPreloadContract(),
) -> dict[str, object]:
    """Build the dependency-image input payload from narrow runtime truth."""
    requirements_lines = [line for line in requirements_text.splitlines() if line.strip() != ""]
    payload: dict[str, object] = {
        "easyocr_preload": easyocr_preload.as_json_object(),
        "requirements_sha256": _sha256_text(requirements_text),
        "runtime_kind": runtime_kind,
        "runtime_pins": runtime_pins,
        "schema_version": SCHEMA_VERSION,
        "service_requirements": requirements_lines,
    }
    payload["dependency_hash"] = dependency_input_hash(payload)
    return payload


def build_project_dependency_input_payload(
    *,
    project_root: Path,
    requirements_text: str,
    runtime_kind: RuntimeKind,
) -> dict[str, object]:
    """Build a dependency-image input payload from repo-local selected fields."""
    if runtime_kind == "rocm":
        runtime_pins = rocm_runtime_pins_json(load_rocm_runtime_contract(project_root))
    else:
        runtime_pins = cpu_runtime_pins_json(load_cpu_runtime_contract(project_root))
    return build_dependency_input_payload(
        requirements_text=requirements_text,
        runtime_kind=runtime_kind,
        runtime_pins=runtime_pins,
    )


def write_dependency_inputs(
    *,
    project_root: Path,
    requirements_path: Path,
    output_dir: Path,
    runtime_kind: RuntimeKind,
) -> str:
    """Write runtime env files plus dependency input JSON and return its hash."""
    output_dir.mkdir(parents=True, exist_ok=True)
    requirements_text = requirements_path.read_text(encoding="utf-8")
    rocm_contract = load_rocm_runtime_contract(project_root)
    cpu_contract = load_cpu_runtime_contract(project_root)

    (output_dir / "rocm-runtime.env").write_text(
        rocm_contract.as_shell_exports(),
        encoding="utf-8",
    )
    (output_dir / "cpu-runtime.env").write_text(
        cpu_contract.as_shell_exports(),
        encoding="utf-8",
    )

    payload = build_project_dependency_input_payload(
        project_root=project_root,
        requirements_text=requirements_text,
        runtime_kind=runtime_kind,
    )
    dependency_hash = str(payload["dependency_hash"])
    (output_dir / f"service-dependency-inputs-{runtime_kind}.json").write_text(
        _canonical_json(payload),
        encoding="utf-8",
    )
    return dependency_hash


def _parse_args() -> argparse.Namespace:
    """Parse command-line arguments for dependency input generation."""
    parser = argparse.ArgumentParser(
        description="Generate narrow service dependency image input artifacts."
    )
    parser.add_argument(
        "--project-root",
        type=Path,
        required=True,
        help="Repository root containing pyproject.toml.",
    )
    parser.add_argument(
        "--requirements",
        type=Path,
        required=True,
        help="Filtered service requirements file to include in the dependency contract.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        required=True,
        help="Directory where dependency input artifacts should be written.",
    )
    parser.add_argument(
        "--runtime",
        choices=("rocm", "cpu"),
        required=True,
        help="Runtime dependency lane to hash.",
    )
    return parser.parse_args()


def _runtime_kind_from_arg(value: str) -> RuntimeKind:
    """Return a validated runtime kind from argparse text."""
    if value == "rocm":
        return "rocm"
    if value == "cpu":
        return "cpu"
    raise ValueError(f"unsupported runtime kind: {value}")


def main() -> None:
    """Generate dependency input artifacts and print the dependency hash."""
    args = _parse_args()
    dependency_hash = write_dependency_inputs(
        project_root=args.project_root,
        requirements_path=args.requirements,
        output_dir=args.output_dir,
        runtime_kind=_runtime_kind_from_arg(args.runtime),
    )
    print(dependency_hash)


if __name__ == "__main__":
    main()
