"""Generate deterministic documentation doorway and lane indexes.

Purpose:
    Keep `docs/index.md` and generated lane `INDEX.md` files synchronized with
    the repository's docs-as-code frontmatter instead of maintaining navigation
    by hand.

Relationships:
    - Invoked by `pdm run index-docs` and `pdm run docs-sync`.
    - Validated by `scripts.docs_as_code.validate_docs`.
    - Uses `scripts.docs_as_code.common` for repository paths and dates.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import date
from pathlib import Path

import yaml

from scripts.docs_as_code.common import BACKLOG_DIR, DOCS_DIR, ROOT, today_iso

FRONTMATTER_RE = re.compile(r"\A---\s*\n(.*?)\n---\s*\n", re.DOTALL)
GENERATED_COMMENT = "<!-- Generated by `pdm run docs-sync`; do not edit by hand. -->"


@dataclass(frozen=True)
class IndexDocument:
    """Normalized document metadata rendered into generated indexes."""

    doc_id: str
    title: str
    doc_type: str
    status: str
    path: Path


@dataclass(frozen=True)
class GeneratedIndex:
    """Generated index target and rendered content."""

    path: Path
    content: str


def repo_relative(path: Path) -> str:
    """Return a stable repository-relative path string."""
    return str(path.relative_to(ROOT)).replace("\\", "/")


def markdown_link(target: Path, source: Path) -> str:
    """Return a relative markdown link from one generated file to a target."""
    return str(target.relative_to(source.parent)).replace("\\", "/")


def parse_frontmatter(path: Path) -> dict[str, object]:
    """Read a markdown file's YAML frontmatter as a mapping."""
    text = path.read_text(encoding="utf-8", errors="replace")
    match = FRONTMATTER_RE.match(text)
    if match is None:
        return {}
    raw = yaml.safe_load(match.group(1)) or {}
    if not isinstance(raw, dict):
        return {}
    return {str(key): value for key, value in raw.items()}


def existing_created_date(path: Path) -> str:
    """Return an existing generated file's created date, or today's date."""
    if not path.exists():
        return today_iso()
    frontmatter = parse_frontmatter(path)
    value = frontmatter.get("created")
    if isinstance(value, str) and value.strip():
        return value.strip()
    if isinstance(value, date):
        return value.isoformat()
    return today_iso()


def render_frontmatter(fields: dict[str, object]) -> str:
    """Render deterministic YAML frontmatter for generated docs."""
    lines = ["---"]
    for key, value in fields.items():
        if isinstance(value, list):
            if not value:
                lines.append(f"{key}: []")
                continue
            lines.append(f"{key}:")
            for item in value:
                lines.append(f"  - {item}")
            continue
        lines.append(f"{key}: {value}")
    lines.append("---")
    return "\n".join(lines)


def collect_documents(root: Path, pattern: str, excluded_names: set[str]) -> list[IndexDocument]:
    """Collect indexed markdown documents below a root path."""
    documents: list[IndexDocument] = []
    for path in sorted(root.glob(pattern)):
        if not path.is_file() or path.name in excluded_names:
            continue
        frontmatter = parse_frontmatter(path)
        doc_id = str(frontmatter.get("id", "")).strip()
        title = str(frontmatter.get("title", "")).strip()
        doc_type = str(frontmatter.get("type", "")).strip()
        status = str(frontmatter.get("status", "")).strip()
        if not doc_id or not title:
            continue
        documents.append(
            IndexDocument(
                doc_id=doc_id,
                title=title,
                doc_type=doc_type,
                status=status,
                path=path,
            )
        )
    return documents


def render_document_table(documents: list[IndexDocument], output_path: Path) -> list[str]:
    """Render a stable markdown table for indexed documents."""
    if not documents:
        return ["No indexed documents."]

    lines = [
        "| ID | Title | Type | Status |",
        "|---|---|---|---|",
    ]
    for document in sorted(documents, key=lambda item: (item.doc_type, item.doc_id)):
        link = markdown_link(document.path, output_path)
        lines.append(
            "| "
            f"{escape_table_cell(document.doc_id)} | "
            f"[{escape_table_cell(document.title)}]({link}) | "
            f"{escape_table_cell(document.doc_type)} | "
            f"{escape_table_cell(document.status)} |"
        )
    return lines


def escape_table_cell(value: str) -> str:
    """Escape markdown table cell text to keep generated indexes formatter-stable."""
    return value.replace("\\", "\\\\").replace("|", "\\|").replace("<", "\\<")


def render_generated_doc(
    *,
    path: Path,
    frontmatter: dict[str, object],
    body_lines: list[str],
) -> GeneratedIndex:
    """Build a generated markdown document with frontmatter and body."""
    content = "\n".join(
        [
            render_frontmatter(frontmatter),
            "",
            GENERATED_COMMENT,
            "",
            *body_lines,
            "",
        ]
    )
    return GeneratedIndex(path=path, content=content)


def build_backlog_index() -> GeneratedIndex:
    """Build the generated backlog lane index."""
    output_path = BACKLOG_DIR / "INDEX.md"
    documents = collect_documents(
        BACKLOG_DIR,
        "**/*.md",
        excluded_names={"INDEX.md", "README.md"},
    )
    body = [
        "## Purpose",
        "",
        "Generated index for backlog planning documents.",
        "",
        "## Documents",
        "",
        *render_document_table(documents, output_path),
    ]
    return render_generated_doc(
        path=output_path,
        frontmatter={
            "id": "backlog-index",
            "title": "Backlog Index",
            "type": "reference",
            "status": "active",
            "priority": "medium",
            "created": existing_created_date(output_path),
            "last_updated": today_iso(),
            "related": [],
            "labels": ["generated", "index"],
        },
        body_lines=body,
    )


def build_reference_index() -> GeneratedIndex:
    """Build the generated reference lane index."""
    output_path = DOCS_DIR / "reference" / "INDEX.md"
    documents = collect_documents(output_path.parent, "*.md", excluded_names={"INDEX.md"})
    body = [
        "## Purpose",
        "",
        "Generated index for reference, research, review, and roadmap documents.",
        "",
        "## Documents",
        "",
        *render_document_table(documents, output_path),
    ]
    return render_generated_doc(
        path=output_path,
        frontmatter={
            "type": "reference",
            "id": "REF-reference-index",
            "title": "Reference Index",
            "status": "active",
            "created": existing_created_date(output_path),
            "last_updated": today_iso(),
            "owners": ["platform"],
            "labels": ["generated", "index"],
        },
        body_lines=body,
    )


def build_runbook_index() -> GeneratedIndex:
    """Build the generated runbook lane index."""
    output_path = DOCS_DIR / "runbooks" / "INDEX.md"
    documents = collect_documents(output_path.parent, "*.md", excluded_names={"INDEX.md"})
    body = [
        "## Purpose",
        "",
        "Generated index for operational runbooks.",
        "",
        "## Documents",
        "",
        *render_document_table(documents, output_path),
    ]
    return render_generated_doc(
        path=output_path,
        frontmatter={
            "type": "runbook",
            "id": "RUN-runbook-index",
            "title": "Runbook Index",
            "status": "active",
            "created": existing_created_date(output_path),
            "last_updated": today_iso(),
            "owners": ["platform"],
            "system": "docs",
            "labels": ["generated", "index"],
        },
        body_lines=body,
    )


def build_root_index() -> GeneratedIndex:
    """Build the generated root documentation doorway."""
    output_path = DOCS_DIR / "index.md"
    body = [
        "## Purpose",
        "",
        "Root doorway for active Sir Convert-a-Lot documentation.",
        "",
        "## Generated Lanes",
        "",
        "- [Backlog Index](backlog/INDEX.md)",
        "- [Reference Index](reference/INDEX.md)",
        "- [Runbook Index](runbooks/INDEX.md)",
        "",
        "## Authoritative Surfaces",
        "",
        "- [Docs Structure Spec](DOCS_STRUCTURE_SPEC.md)",
        "- [Docs Contract](_meta/docs-contract.yaml)",
        "- [Backlog Guide](backlog/README.md)",
        "- [Converter and API Contracts](converters/)",
        "- [Decisions](decisions/)",
        "- [Product Direction](pdr/)",
    ]
    return render_generated_doc(
        path=output_path,
        frontmatter={
            "type": "spec",
            "id": "SPEC-docs-index",
            "title": "Sir Convert-a-Lot Documentation Index",
            "status": "active",
            "created": existing_created_date(output_path),
            "owners": ["platform"],
            "tags": ["generated", "index"],
        },
        body_lines=body,
    )


def build_generated_indexes() -> list[GeneratedIndex]:
    """Build all generated docs indexes in dependency order."""
    return [
        build_backlog_index(),
        build_reference_index(),
        build_runbook_index(),
        build_root_index(),
    ]


def write_generated_indexes() -> list[Path]:
    """Write all generated indexes and return their paths."""
    written: list[Path] = []
    for generated in build_generated_indexes():
        generated.path.parent.mkdir(parents=True, exist_ok=True)
        generated.path.write_text(generated.content, encoding="utf-8")
        written.append(generated.path)
    return written


def validate_generated_indexes() -> list[str]:
    """Return freshness violations for generated index files."""
    violations: list[str] = []
    for generated in build_generated_indexes():
        if not generated.path.exists():
            violations.append(
                f"{repo_relative(generated.path)}: missing generated index; run `pdm run docs-sync`"
            )
            continue
        actual = generated.path.read_text(encoding="utf-8")
        if actual != generated.content:
            violations.append(
                f"{repo_relative(generated.path)}: stale generated index; run `pdm run docs-sync`"
            )
    return violations


def main() -> None:
    """Regenerate all docs index files."""
    for path in write_generated_indexes():
        print(repo_relative(path))


if __name__ == "__main__":
    main()
