"""Tests for the service image requirements export helper.

Purpose:
    Protect the filtered production-requirements contract used by the service
    Dockerfile so CUDA-flavoured torch packages do not sneak back into the
    runtime dependency layer.

Relationships:
    - Covers `scripts.sir_convert_a_lot.devops.export_service_requirements`.
    - Supports the service image layering contract in the root `Dockerfile`.
"""

from __future__ import annotations

from scripts.sir_convert_a_lot.devops.export_service_requirements import (
    filter_requirement_lines,
)


def test_filter_requirement_lines_drops_torch_and_cuda_requirements() -> None:
    raw_requirements = "\n".join(
        [
            "docling==2.73.1",
            "easyocr==1.7.2",
            'cuda-bindings==12.9.4; platform_system == "Linux"',
            "torch==2.10.0",
            "torchvision==0.25.0",
            "torchaudio==2.10.0",
            'triton==3.6.0; platform_system == "Linux"',
            'nvidia-cudnn-cu12==9.10.2.21; platform_system == "Linux"',
            "",
        ]
    )

    filtered_requirements = filter_requirement_lines(raw_requirements)

    assert "docling==2.73.1" in filtered_requirements
    assert "easyocr==1.7.2" in filtered_requirements
    assert "cuda-bindings==12.9.4" not in filtered_requirements
    assert "torch==2.10.0" not in filtered_requirements
    assert "torchvision==0.25.0" not in filtered_requirements
    assert "torchaudio==2.10.0" not in filtered_requirements
    assert "triton==3.6.0" not in filtered_requirements
    assert "nvidia-cudnn-cu12==9.10.2.21" not in filtered_requirements


def test_filter_requirement_lines_preserves_internal_identity_crypto_dependency() -> None:
    raw_requirements = "\n".join(
        [
            "cryptography==46.0.5",
            "cffi==2.0.0",
            "",
        ]
    )

    filtered_requirements = filter_requirement_lines(raw_requirements)

    assert "cryptography==46.0.5" in filtered_requirements
    assert "cffi==2.0.0" in filtered_requirements


def test_filter_requirement_lines_preserves_comments_and_non_matching_lines() -> None:
    raw_requirements = "\n".join(
        [
            "# generated by pdm export",
            "--extra-index-url https://example.invalid/simple",
            "opencv-python-headless==4.13.0.92",
            "pillow==12.1.1",
            "",
        ]
    )

    filtered_requirements = filter_requirement_lines(raw_requirements)

    assert "# generated by pdm export" in filtered_requirements
    assert "--extra-index-url https://example.invalid/simple" in filtered_requirements
    assert "opencv-python-headless==4.13.0.92" in filtered_requirements
    assert "pillow==12.1.1" in filtered_requirements
